//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ConsoleApp2.MerchantToken {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MerchantTokens_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/MerchantTokens")]
    public partial class MerchantTokens : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PutMerchantTokensOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MerchantTokens() {
            this.Url = global::ConsoleApp2.Properties.Settings.Default.ConsoleApp2_MerchantToken_MerchantTokens;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PutMerchantTokensCompletedEventHandler PutMerchantTokensCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/MerchantTokens:PutMerchantTokens", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/MerchantTokens", ResponseElementName="PutMerchantTokens_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/MerchantTokens", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PutMerchantTokens(string accessToken, string refreshToken) {
            this.Invoke("PutMerchantTokens", new object[] {
                        accessToken,
                        refreshToken});
        }
        
        /// <remarks/>
        public void PutMerchantTokensAsync(string accessToken, string refreshToken) {
            this.PutMerchantTokensAsync(accessToken, refreshToken, null);
        }
        
        /// <remarks/>
        public void PutMerchantTokensAsync(string accessToken, string refreshToken, object userState) {
            if ((this.PutMerchantTokensOperationCompleted == null)) {
                this.PutMerchantTokensOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPutMerchantTokensOperationCompleted);
            }
            this.InvokeAsync("PutMerchantTokens", new object[] {
                        accessToken,
                        refreshToken}, this.PutMerchantTokensOperationCompleted, userState);
        }
        
        private void OnPutMerchantTokensOperationCompleted(object arg) {
            if ((this.PutMerchantTokensCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PutMerchantTokensCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void PutMerchantTokensCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591